### ISSUE TITLE
Polygon.Difference fails against rotated Polygons

### ISSUE THREAD

**Issue by anthonyhauck** [hypar-io/Elements#358]
**Describe the bug**
Rotated Polygons generate errors when combined using Polygon.Difference. Either partial results are returned, or new Polygons fail with intersecting segments.

**To Reproduce**

        [Fact]
        public void DifferenceTest()
        {
            var SUBTRACT = true; //set to false to see all Polygons used.
            var ROTATE = 47.0; //this case has failed in the past, as does 90.0

            var tR = new Transform(Vector3.Origin, ROTATE);
            var polygon = tR.OfPolygon(Polygon.Rectangle(Vector3.Origin, new Vector3(100.0, 50.0)));
            var subtract = Polygon.Rectangle(Vector3.Origin, new Vector3(1.0, 20.0));
            var subtracts = new List<Polygon>();
            for (var i = 1; i < 99; i++)
            {
                subtracts.Add(tR.OfPolygon(subtract.MoveFromTo(Vector3.Origin, new Vector3(i, 0.0))));
            }
            subtract = Polygon.Rectangle(new Vector3(0.0, 30.0), new Vector3(1.0, 50.0));
            for (var i = 1; i < 99; i++)
            {
                subtracts.Add(tR.OfPolygon(subtract.MoveFromTo(Vector3.Origin, new Vector3(i, 0.0))));
            }
            var polygons = new List<Polygon>();
            if (SUBTRACT)
            {
                polygons.AddRange(polygon.Difference(subtracts));
            }
            else
            {
                polygons.Add(polygon);
            }
            var matl = new Material(Palette.Aqua, 0.0, 0.0, false, null, false, Guid.NewGuid(), "space");
            var model = new Model();
            foreach (var shape in polygons)
            {
                model.AddElement(new Space(shape, 0.1, BuiltInMaterials.Concrete));
            }
            foreach (var shape in subtracts)
            {
                model.AddElement(new Space(shape, 4.0, matl));
            }
            //TODO: Add a sensible Assert() because this test just writes out for visual inspection.
            model.ToGlTF("../../../../testOutput/Shaper.DifferenceTest.glb");
        }

// Called from above test
 public static Polygon MoveFromTo(this Polygon polygon, Vector3 from, Vector3 to)
        {
            var t = new Transform(new Vector3(to.X - from.X, to.Y - from.Y, to.Z - from.Z));
            return t.OfPolygon(polygon);
        }

**Expected behavior**
Rotated Polygons should return expected Polygon differences.

**Screenshots**
![image](https://user-images.githubusercontent.com/33582525/89052795-3d5cd980-d324-11ea-84f7-bc297b7bd3f7.png)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**

**Comment by anthonyhauck** [comment]
Adding PolyFillType.pftNonZero has limited success in the method below.
Rotation of 0.0, 45.0, and 90.0 work fine.
Rotation of 47.0 or 88.0 returns a difference of little edge strips along the long sides of the original polygon in the test above.

public static List<Polygon> Differences(Polygon polygon, List<Polygon> difPolys)
        {
            var polygons = new List<Polygon>();
            var clipper = new Clipper();
            clipper.AddPath(polygon.ToClipperPath(), PolyType.ptSubject, true);
            difPolys = Shaper.Merge(difPolys);
            foreach (Polygon differ in difPolys)
            {
                clipper.AddPath(differ.ToClipperPath(), PolyType.ptClip, true);
            }
            var solution = new List<List<IntPoint>>();
            clipper.Execute(ClipType.ctDifference, solution, PolyFillType.pftNonZero);
            if (solution.Count == 0)
            {
                return polygons;
            }
            foreach (List<IntPoint> path in solution)
            {
                var diff = ToPolygon(path);
                if (diff == null)
                {
                    continue;
                }
                if (diff.IsClockWise())
                {
                    diff = diff.Reversed();
                }
                polygons.Add(diff);
            }
            return Merge(polygons).OrderByDescending(p => Math.Abs(p.Area())).ToList();
        }

**Comment by anthonyhauck** [comment]
After more investigation, I believe the issue is not the FillType, but the Clipper scaling constant in Elements. I get an increasing number of successes at odd angles the higher that constant is. In the GeometryEx mirror universe, the value commonly successful so far 10000000000.0 (10 billion) -- I haven't tuned this yet but changing this constant from 1024.0 has an immediate positive effect on results. In fact, this value is probably too high, as it begins to generate some extra difference along the perimeter of the test case. I think the conversion into and out of Clipper might be better served by some sort of proportional scaling, perhaps based on the bounding box of the polygon in question (but I have to think about that more).

**Comment by ikeough** [comment]
@andrewheumann Is this fixed with the improvement above?

**Comment by andrewheumann** [comment]
This is improved but not fixed all the way. Clipper is fundamentally incapable of handling this case with coincident edges of angled polygons because of the way it uses integers. 
![rounding issue](https://user-images.githubusercontent.com/31935763/90564094-c6706f00-e172-11ea-8cb0-a7c48440c7f9.gif)

**Comment by andrewheumann** [comment]
closing as a wontfix / sort of fixed
